sudo: false
language: python

python:
    - 2.6
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - 3.6-dev

install:
    - pip install -r test-requirements.txt

script:
    - pytest

notifications:
    email: false
